debug: add tar check

diff --git a/.github/workflows/build-docker-image.yaml b/.github/workflows/build-docker-image.yaml
--- a/.github/workflows/build-docker-image.yaml
+++ b/.github/workflows/build-docker-image.yaml
@@ -63,6 +63,16 @@ jobs:
           key: build-artifacts-${{ matrix.tag }}-
           restore-keys: |
             build-artifacts-${{ matrix.tag }}-
+      - name: Check contents of restored tar files
+        run: |
+          echo "Checking contents of install.tar.gz:"
+          tar -tzf ${{ github.workspace }}/cache/install.tar.gz || echo "install.tar.gz is empty or invalid"
+          echo "Checking contents of build.tar.gz:"
+          tar -tzf ${{ github.workspace }}/cache/build.tar.gz || echo "build.tar.gz is empty or invalid"
+          echo "Checking contents of log.tar.gz:"
+          tar -tzf ${{ github.workspace }}/cache/log.tar.gz || echo "log.tar.gz is empty or invalid"
+          echo "Checking contents of src.tar.gz:"
+          tar -tzf ${{ github.workspace }}/cache/src.tar.gz || echo "src.tar.gz is empty or invalid"
 
       - name: Set up Docker image tag
         run: echo "DOCKER_IMAGE_TAG=ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/${{ env.DOCKER-IMAGE }}:${{ matrix.tag }}" >> $GITHUB_ENV
